### ISSUE TITLE
Autocomplete proposes localized values (e.g. Country), that don't work to trigger alerts

### ISSUE THREAD

**Issue by peterbo** [matomo-org/plugin-CustomAlerts#113]
When setting up an alert for e.g. Visits "applies to report: Country" that "is not" - autocomplete proposes the localized country name, e.g. "Deutschland". But this doesn't work, since the alert does not convert the localized country name back to how it is stored, when searching for alert conditions ("Germany" works).

**Comment by tsteur** [comment]
@peterbo any chance you can try a patch? I would assume that 

```
diff --git a/plugins/CustomAlerts/angularjs/managecustomalerts/managecustomalerts.controller.js b/plugins/CustomAlerts/angularjs/managecustomalerts/managecustomalerts.controller.js
index 7ad2012dc..d1a95757c 100644
--- a/plugins/CustomAlerts/angularjs/managecustomalerts/managecustomalerts.controller.js
+++ b/plugins/CustomAlerts/angularjs/managecustomalerts/managecustomalerts.controller.js
@@ -250,6 +250,7 @@
                 showColumns: metric,
                 apiModule: apiModule,
                 apiAction: apiAction,
+                language: 'en',
                 idSite: self.alert.site.id,
                 format: 'JSON'
             }).then(function (data) {
```

Makes this work. I checked the API request and it then is returned in English. It's not ideal but would make it work.

**Comment by peterbo** [comment]
@tsteur Thanks, Thomas! Workaround is working.
