### ISSUE TITLE
Table 'matomo.matomo_alert' doesn't exist

### ISSUE THREAD

**Issue by Kahuna26** [matomo-org/plugin-CustomAlerts#131]
Hi,

After the installation of this plugin we recieve the follow error:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'matomo.matomo_alert' doesn't exist.

We are using a cluster matomo setup with 2 nodes and install the plugins using a python script so the nodes don't get confused. 
For some reason the needed table is not created, i would like to add the table myself but i don't know the data needed to create this table. 

Please advice.

**Comment by tsteur** [comment]
@Kahuna26 sorry about that. Is there any chance you can edit the config file on our Matomo installation? If so, could you locate the file `config/config.ini.php` in your Matomo installation, remove the line that says `PluginsInstalled[] = "CustomAlerts"` and save the change. Then try to access your Matomo again. This should trigger Matomo to install the missing table.

Alternatively, the current table definition is below. Note that the table is called `matomo_alert` but if you configured a custom table prefix, then this may be different.

```sql
CREATE TABLE `matomo_alert` (
  `idalert` int NOT NULL,
  `name` varchar(100) NOT NULL,
  `login` varchar(100) NOT NULL,
  `period` varchar(5) NOT NULL,
  `report` varchar(150) NOT NULL,
  `report_condition` varchar(50) DEFAULT NULL,
  `report_matched` varchar(255) DEFAULT NULL,
  `metric` varchar(150) NOT NULL,
  `metric_condition` varchar(50) NOT NULL,
  `metric_matched` float NOT NULL,
  `compared_to` smallint unsigned NOT NULL DEFAULT '1',
  `email_me` tinyint(1) NOT NULL DEFAULT '0',
  `additional_emails` text,
  `phone_numbers` text,
  PRIMARY KEY (`idalert`)
)
```

**Comment by Kahuna26** [comment]
Hi Thomas. 

Thank you for your quick response.
I will give this a try!

**Comment by Kahuna26** [comment]
HI Thomas,

Removing the line PluginsInstalled[] = "CustomAlerts" did the trick. 
This works for one instance (a matomo 3.13.1) for another intance (matomo 4.10.1) i can only see the banner "Manage Custom Alerts" but no other options to create or manage an alert are visible.

**Comment by tsteur** [comment]
@Kahuna26 could you maybe try to upgrade the instance 4.10.1 that doesn't show both options to the latest version of Matomo?

**Comment by AltamashShaikh** [comment]
Closing this due to no further response from the user
