### ISSUE TITLE
Alert conditions for Events are misleading

### ISSUE THREAD

**Issue by utrautmann** [matomo-org/plugin-CustomAlerts#135]
Conditions for events give the possibility to compare with event category, action and name.
Contrary to this clear labeling and expectation, however, the comparison takes place with either "_Category - Action_", "_Action-Name_" or "_Name-Action_".
If I don't know that as a user, then I do an "is comparison" e.g. with the action, which will never apply. See screenshot please

It would be better if either the labels are changed (f.e. category - action) or the comparison works as expected from the labels.

**Example:**
This will never apply:
![grafik](https://user-images.githubusercontent.com/25771066/222400416-cc5a63fc-d14c-42f4-9c74-926dfd023b31.png)

Because of the comparison will only happen to "action - name":
![grafik](https://user-images.githubusercontent.com/25771066/222400955-ee539555-b3a9-4bf1-a4d2-84cfe95ba2d3.png)

**Comment by snake14** [comment]
Hi @utrautmann . Thank you for taking the time to create this issue. It sounds like the behaviour isn't as expected. I'm going to add this to the backlog for prioritisation. We can evaluate how to update the messaging and/or functionality to better meet the needs of our customers.

**Comment by utrautmann** [comment]
@snake14 , @innocraft-automation 
what means "closed this as completed"? is this really solved?

**Comment by snake14** [comment]
Hi @utrautmann . It looks like it was closed because [more help text was added](https://github.com/matomo-org/plugin-CustomAlerts/pull/159) to help explain the inputs. That will be part of the next release of the plugin within the next couple weeks.
