### ISSUE TITLE
Add autocompletion to the value field

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/plugin-CustomAlerts#136]
Hi team,

Currently there isn't an auto completion field for the custom alert plugin.
So to say, if you select a report, let's say continent, it does not show you the list of possible values (so as it would be for segments).

--> Would it be possible to make this feature available?

Thank you

**Comment by snake14** [comment]
Hi @Chardonneaur . Thank you for taking the time to create this issue. That sounds like a good suggestion for an improvement. I'll mark this issue for prioritisation.

**Comment by Stan-vw** [comment]
Thanks for the suggestion @Chardonneaur. I've had a look to try and understand your suggestion better, but I'm not sure if I fully understood it. Attached are some screenshots of the value field, showing the current autocomplete logic. 

In the continent field it seems reasonable to "show the list all possible values" even when nothing is typed, but as you see in the device model screenshot it's not that straightforward for some other fields. Additionally, it makes sense to show all continents when you use the "is"-condition, but not when selecting "ends with"-condition.

It'd be great if you could elaborate further on the value that you're after / problem that you're experiencing.

Thanks
![Screen Shot 2023-03-09 at 11 14 02 AM](https://user-images.githubusercontent.com/52564377/223866029-da0ab479-97cc-4779-bfd5-fe09c0a4d48e.png)
![Screen Shot 2023-03-09 at 11 29 38 AM](https://user-images.githubusercontent.com/52564377/223866043-08cf739f-4e59-4ffe-8873-d4c3ccda9909.png)
![Screen Shot 2023-03-09 at 11 13 43 AM](https://user-images.githubusercontent.com/52564377/223866058-374a3f19-07b1-41fb-88f2-8716b7fda397.png)

**Comment by Chardonneaur** [comment]
Hi Stan,

Thank you for your answer, my bad, i just checked it back and it works. Maybe I was looking at a site which had few data so nothing was showing up.
