### ISSUE TITLE
Alert definition input fields can be too small

### ISSUE THREAD

**Issue by mattab** [matomo-org/plugin-CustomAlerts#22]
See screenshot on 2.15.0 and latest CustomAlerts: input fields and Select boxes are slightly too small to fit the numbers and strings:

* Input box too small for text to fit
* Select box text is too wide and overlaps

![invisible inputs](https://cloud.githubusercontent.com/assets/466765/10835384/9fc889f6-7f06-11e5-9bd0-2ed720e4371c.png)

**Comment by sgiehl** [comment]
What would be a good solution for this? Having bigger drop downs, maybe by autoadjusting the size based on the longest option? Or fading out the text, so the arrow is better visible (like in piwik/piwik#9414)

**Comment by mattab** [comment]
works
