### ISSUE TITLE
some small design problems

### ISSUE THREAD

**Issue by hpvd** [matomo-org/plugin-CustomAlerts#28]
some small design problems:
- not enough room within dropdowns (similar to https://github.com/piwik/plugin-CustomAlerts/issues/27 and https://github.com/piwik/plugin-CustomAlerts/issues/22 )
- changing spaces between rows

maybe this should be fixed after looking at https://github.com/piwik/plugin-CustomAlerts/issues/26

please see attachements
all from FF and plugin v0.1.22

![2016-01-14_23h05_07](https://cloud.githubusercontent.com/assets/5681880/12339354/027b8f54-bb15-11e5-8f93-6f1bf7971a83.png)
![2016-01-14_23h06_51](https://cloud.githubusercontent.com/assets/5681880/12339361/0b5ef1c4-bb15-11e5-997c-729aae633c46.png)
![2016-01-14_23h08_28](https://cloud.githubusercontent.com/assets/5681880/12339364/0f03ccc8-bb15-11e5-88d9-f88d6a6331a6.png)

**Comment by hpvd** [comment]
maybe one should think about solving the "not enough room within dropdowns"-problem with some kind of dynamic width to prevent problems when texts get even longer in other languages.
To have always enough space, one could have only **one** dynamic width **input field per row**.

=> what do you think?

**Comment by adamreng** [comment]
@hpvd Current UI has changed to be significantly different than what's in the screenshots. Closing this issue for now. Feel free to reopen if you still see any issues.
