### ISSUE TITLE
is Plugin broken in Matomo 3.5.1?

### ISSUE THREAD

**Issue by SBejga** [matomo-org/plugin-CustomAlerts#48]
Hi, 

I just installed the plugin in my matomo instance, and when I open "Alerts" at "Personal" Section in Administration. The form is empty except the alert name input field. But there should be much more input fields (I guess 😄).

System check is green

![screen shot 2018-07-26 at 23 32 01](https://user-images.githubusercontent.com/67571/43289812-66697374-912c-11e8-80a2-7e8c6693d111.png)

**Comment by mattab** [comment]
Can you try again to update Matomo to 3.6.0 and the plugin? it should work and works well for us
