### ISSUE TITLE
No option to alert on avg generation time [Support processed metrics]

### ISSUE THREAD

**Issue by thegodmonkey** [matomo-org/plugin-CustomAlerts#63]
Options do not seem to have a way to set a custom alert on generation time over/below a value. I believe this an option that I should be expecting?

**Comment by tsteur** [comment]
Adjusted the title that we should basically support processed metrics 👍

**Comment by adamreng** [comment]
@thegodmonkey Avg. page generation time has been deprecated in favor of new metrics in Page Performance plugin. [See here](https://developer.matomo.org/api-reference/Piwik/Plugins/Actions/Columns/Metrics/AveragePageGenerationTime). If you would still like changes to be made then feel free to reopen the issue.
