### ISSUE TITLE
Can't create new alert

### ISSUE THREAD

**Issue by quikina** [matomo-org/plugin-CustomAlerts#64]
When I click the ‘Create New Alert’ I get the following form displayed, that can't be sent.
[https://forum.matomo.org/uploads/db1181/original/2X/5/59b07bd09f067aa98ca7e2a4bb3eb5ea32cd0f61.png](https://forum.matomo.org/uploads/db1181/original/2X/5/59b07bd09f067aa98ca7e2a4bb3eb5ea32cd0f61.png)

**Comment by sgiehl** [comment]
@quikina  could you check the browser console for errors or failures in loading data?

**Comment by quikina** [comment]
there's this error message in browser console:
Error: "[$controller:ctrlreg] http://errors.angularjs.org/1.6.5/$controller/ctrlreg?p0=ManagecustomalertsController"

**Comment by sgiehl** [comment]
Ok. Seems the javascript file couldn't be loaded correctly maybe. Could you check if the file `plugins\CustomAlerts\angularjs\managecustomalerts\managecustomalerts.controller.js` exists?

**Comment by quikina** [comment]
Yes it does

**Comment by sgiehl** [comment]
Can you see if that file fails to load in the browser?

**Comment by quikina** [comment]
Can't find the file.
This is the full error message: 
https://forum.matomo.org/uploads/db1181/original/2X/8/866f0c56dbf3cac906de767df25491254f78b754.png

**Comment by tsteur** [comment]
Is there any chance you could empty your `$matomoDir/tmp/*` cache folder or execute the command `./console cache:clear` within your Matomo directory? Just in case it fixes it? Probably won't but worth a try.

**Comment by quikina** [comment]
I just executed ./console cache:clear but nothing has changed

**Comment by sgiehl** [comment]
Guess you already tried clearing the browser cache?

**Comment by quikina** [comment]
Yes I cleared the browser cache, I have also tried to create alerts in different browsers.

**Comment by tsteur** [comment]
Could you create a log in for us to your Matomo?  If so, be great to email us: https://matomo.org/contact/

**Comment by tsteur** [comment]
A user with write permission be enough. Just so we can reproduce it and investigate

**Comment by tsteur** [comment]
@quikina in case you could solve the issue be great to know how you fixed it. Cheers
